modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="light"
version="1.0.0"
displayName="light"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="FEL1X TeA"
description='''
随手制作的
'''

[[dependencies.light]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




